apiVersion: v1
kind: Service
metadata:
  name: {{ include "unfold.fullname" . }}-frontend
  labels:
    {{- include "unfold.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "unfold.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
