{{- if .Values.neo4j.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unfold.fullname" . }}-neo4j
  labels:
    {{- include "unfold.labels" . | nindent 4 }}
    app.kubernetes.io/component: neo4j
spec:
  type: {{ .Values.neo4j.service.type }}
  ports:
    - port: {{ .Values.neo4j.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.neo4j.service.boltPort }}
      targetPort: bolt
      protocol: TCP
      name: bolt
  selector:
    {{- include "unfold.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: neo4j
{{- end }}
