frontend:
  replicaCount: 1
  image:
    repository: kr4t0n/unfold-frontend
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}

backend:
  replicaCount: 1
  image:
    repository: kr4t0n/unfold-backend
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}
  neo4j:
    uri: bolt://neo4j:7687
    username: neo4j
    password: changeme
    existingSecret:

ingress:
  enabled: false
  className:
  annotations: {}
  host: unfold.local
  tls: []

